CREATE TABLE [dbo].[TrainerClient]
(
	[TrainerId] UNIQUEIDENTIFIER NOT NULL,
	[ClientId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_Trainer_Client PRIMARY KEY ([TrainerId], [ClientId]),
	CONSTRAINT FK_Traiener FOREIGN KEY ([TrainerId]) REFERENCES [dbo].[Trainer]([Id]) ON DELETE CASCADE,
	CONSTRAINT FK_Client FOREIGN KEY ([ClientId]) REFERENCES [dbo].[Client]([Id]) ON DELETE CASCADE
)
